### ISSUE TITLE
Nimony: basic todo list

### ISSUE THREAD

**Issue by Araq** [nim-lang/nimony#218]
- [x] explicit type conversions
- [x]  `distinct` types with basic `borrow` support
- [x] `cstring` support. Note: conversion from string to cstring and vice versa are not implicit anymore.
- [x] `ref T` and `ptr T` support plus `nil`
- [x] type bound `=hooks`. The frontend must instantiate these for instantiated generics.
- [x] `for` loop statement and iterators
- [x] basic `system.nim` auto import feature
- [x] Implement `when` statements.
- [x] Implement `isMainModule`. `defined(nimony)` shall always be true.
- [x] #276
- [x] #288
- [x] the `cast` expression
- [x] #258

**Note: If you pick something from this list, mark it as "done" already, extract it into its own issue and assign yourself to it.**

**Comment by metagn** [comment]
> the `module.name` access syntax

Is there anything special to do for module symbols?

**Comment by Araq** [comment]
Well it is not a `(dot ...)` after semchecking but just a `Symbol`. And right now we don't even add module names to the symbol table.

**Comment by metagn** [comment]
I meant the module names, in the original compiler dot qualification is implemented by checking if the first part is a module symbol. Should there be module symbols? Is there anything that isn't obvious to do for them?

**Comment by Araq** [comment]
You need to add `ModuleY ` to sym kind and it would be the first NIF tag "module" that doesn't occur in NIF files. Well it would be used in the side table in programs.nim I guess.
